[package]
name = "csbee"
version = "0.1.6"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
copypasta = "0.10.1"
crossterm = "0.27.0"
polars = { version = "0.40.0", features = ["lazy", "polars-io"] }
polars-sql = "0.40.0"
ratatui = "0.26.3"
